# Load always when launching vim

[[plugins]]
repo = 'Shougo/dein.vim'
depends = ['wsdjeg/dein-ui.vim']

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# https://github.com/vim-jp/vimdoc-ja
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

# https://github.com/neoclide/coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = '''
  if has('win32') || has('win64')
    let g:coc_node_path="C:/Program\ Files/nodejs/node.exe"
  elseif has('mac')
    let g:coc_node_path="~/.nodebrew/current/bin/node"
  endif

  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <F2> <Plug>(coc-rename)

  function! s:show_documentation()
    if &filetype == 'vim'
      execute 'h ' . expand('<cword>')
    elseif CocAction('hasProvider', 'hover')
      call CocActionAsync('doHover')
    else
      call feedkeys('K', 'in')
    endif
  endfunction
  nnoremap <silent> K :call <SID>show_documentation()<CR>

  augroup HighlightCursorHoldedSymbol
    autocmd!
    autocmd CursorHold * silent call CocActionAsync('highlight')
  augroup END

'''

# https://github.com/itchyny/lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  function! CocCurrentFunction()
    return get(b:, 'coc_current_function', '')
  endfunction

  let g:lightline = {
  \ 'colorscheme': 'ayu_dark',
  \ 'active': {
  \   'left': [
  \     [ 'mode', 'paste' ],
  \     [ 'cocstatus', 'currentfunction', 'readonly', 'filename', 'modified' ],
  \   ],
  \   'right': [
  \     [ 'lineinfo' ],
  \     [ 'percent' ],
  \     [ 'fileformat', 'fileencoding', 'filetype' ]
  \   ],
  \   'component_function': {
  \     'cocstatus': 'coc#status()',
  \     'currentfunction': 'CocCurrentFunction'
  \   }},
  \ 'inactive': {
  \   'left': [
  \     [ 'filename' ]
  \   ],
  \   'right': [
  \     [ 'lineinfo' ],
  \     [ 'percent' ]
  \   ]},
  \ 'tabline': {
  \   'left': [
  \     [ 'tabs' ]
  \   ],
  \   'right': [
  \     [ 'close' ]
  \   ]}
  \ }
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

# https://github.com/reireias/vim-cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/dotfiles/vim/cheatsheet.md'
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# https://github.com/mattn/vim-sonictemplate
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '~/dotfiles/vim/template'
'''

[[plugins]]
repo = 'lambdalisue/readablefold.vim'

# https://github.com/Shougo/context_filetype.vim
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# https://github.com/osyo-manga/vim-precious
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

