# Load always when launching vim

[[plugins]]
repo = 'Shougo/dein.vim'
depends = ['wsdjeg/dein-ui.vim']

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# https://github.com/vim-jp/vimdoc-ja
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

# https://github.com/preservim/nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1
  let NERDTreeIgnore = [
        \ 'NTUSER.*$',
        \ '.[oa]$'
        \]
  augroup AutoEnterOnlyGUI
    autocmd!
    autocmd GUIEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTree' | endif
  augroup END
'''

# https://github.com/neoclide/coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  if has('win32') || has('win64')
    let g:coc_node_path="C:/Program\ Files/nodejs/node.exe"
  elseif has('mac')
    let g:coc_node_path="~/.nodebrew/current/bin/node"
  endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tyru/open-browser.vim'

# https://github.com/reireias/vim-cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/dotfiles/common/vim/cheatsheet.md'
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# https://github.com/mattn/vim-sonictemplate
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '~/dotfiles/common/vim/template'
'''

[[plugins]]
repo = 'lambdalisue/readablefold.vim'

