# Lazy loading

# https://github.com/dart-lang/dart-vim-plugin
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
hook_add = '''
  " enable Dart style guide syntax (like 2-space indentation)
  let g:dart_style_guide = 2
'''

# https://github.com/aklt/plantuml-syntax
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']
hook_add = '''
  let g:plantuml_executable_script = expand('$HOME/dotfiles/common/plantuml/txt2plantuml.sh')
'''

# https://github.com/previm/previm/
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  let g:previm_enable_realtime = 1
  if has('win32') || ('win64')
    let g:previm_open_cmd = 'C:\\Program\ Files\ (x86)\\Mozilla\ Firefox\\firefox.exe'
  elseif has('mac')
    let g:previm_open_cmd = 'open -a Firefox.app'
  else
    let g:previm_open_cmd = ''
  endif
  nnoremap <silent> <C-p> :PrevimOpen<CR>
'''

# https://github.com/rust-lang/rust.vim
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

