# Load always when launching vim

[[plugins]]
repo = 'Shougo/dein.vim'
depends = ['wsdjeg/dein-ui.vim']

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# https://github.com/preservim/nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1
  let NERDTreeIgnore = [
        \ 'NTUSER.*$',
        \ '.[oa]$'
        \]
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTree' | endif
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tyru/open-browser.vim'

# https://github.com/previm/previm/
[[plugins]]
repo = 'previm/previm'
hook_add = '''
  let g:previm_enable_realtime = 1
  if has('win32') || ('win64')
    let g:previm_open_cmd = 'C:\\Program\ Files\ (x86)\\Mozilla\ Firefox\\firefox.exe'
  elseif has('mac')
    let g:previm_open_cmd = 'open -a Firefox.app'
  else
    let g:previm_open_cmd = ''
  endif
  nnoremap <silent> <C-p> :PrevimOpen<CR>
'''

# https://github.com/reireias/vim-cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/dotfiles/common/vim/cheatsheet.md'
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# https://github.com/mattn/vim-sonictemplate
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '~/dotfiles/common/vim/template'
'''

[[plugins]]
repo = 'lambdalisue/readablefold.vim'

