[tools]
node = "24"
npm = "latest"
python = "3"

[tasks.git-update]
description = "Git: Update dotfiles"
run = '''
  pushd $HOME/dotfiles
  git fetch --verbose
  popd
'''
alias = 'gfetch'

[tasks.git-upgrade]
description = "Git: Upgrade dotfiles"
run = '''
  pushd $HOME/dotfiles
  git pull --verbose --prune
  popd
'''
alias = 'gpull'

[tasks.homebrew-update]
description = "Homebrew: Update packages info"
run = '''
  if [[ $(which brew) ]]; then
    brew update -v
  fi
'''
alias = 'bfetch'

[tasks.homebrew-clean]
description = "Homebrew: Clean up old packages"
run = '''
  if [[ $(which brew) ]]; then
    brew cleanup -v
  fi
'''
alias = 'bclean'

[tasks.apt-update]
description = "APT: Update package info"
run = '''
  if [[ $(which apt) ]]; then
    sudo apt update -y
  fi
'''
alias = 'afetch'

[tasks.apt-upgrade]
description = "APT: Upgrade packages"
run = '''
  if [[ $(which apt) ]]; then
    sudo apt upgrade -y
  fi
'''
alias = 'apull'

[tasks.apt-clean]
description = "APT: Clean up old packages"
run = '''
  if [[ $(which apt) ]]; then
    sudo apt autoremove -y
    sudo apt autoclean -y
  fi
'''

[tasks.homebrew-upgrade]
description = "Homebrew: Upgrade packages"
run = '''
  if [[ $(which brew) ]]; then
    brew upgrade -v
  fi
'''
alias = 'bpull'

[tasks.mas-upgrade]
description = "Mac App Store: Update apps"
run = '''
  if [[ $(which mas) ]]; then
    mas upgrade
  fi
'''
alias = 'mpull'

[tasks.all-update]
description = "Update all tools and packages"
depends = ["git-update", "apt-update", "homebrew-update"]
run = "echo 'All tools and packages updated.'"
alias = "fetch"

[tasks.all-upgrade]
description = "Upgrade all tools and packages"
depends = ["git-upgrade", "apt-upgrade", "homebrew-upgrade"]
run = "echo 'All tools and packages upgraded.'"
alias = "pull"

[tasks.all-clean]
description = "Clean up all tools and packages"
depends = ["apt-clean", "homebrew-clean"]
run = "echo 'All tools and packages cleaned up.'"
alias = "clean"

