" My vimrc
" vim:set ts=8 sts=2 sw=2 tw=0:
if &compatible
  set nocompatible
endif

" Plugins dir
let s:plugin_dir = expand('~/.vim/bundle/')
" Add runtimepath the dir to install dein.vim
let s:dein_dir = s:plugin_dir . 'repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . s:dein_dir

" If not installed dein.vim, install when vim is opened
augroup PluginInstall
  autocmd!
  autocmd VimEnter * if dein#check_install() | call dein#install() | endif
augroup END

if !isdirectory(s:dein_dir)
  call mkdir(s:dein_dir, 'p')
  silent execute printf('!git clone %s %s', 'https://github.com/Shougo/dein.vim', s:dein_dir)
endif

if dein#load_state(s:plugin_dir)
  call dein#begin(s:plugin_dir)

  let g:dein_toml_dir = expand('~/dotfiles/common/vim/dein')
  let s:toml = g:dein_toml_dir . '/dein.toml'
  let s:lazy_toml = g:dein_toml_dir . '/dein_lazy.toml'
  call dein#load_toml(s:toml, {'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy': 1})

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on

augroup ExtendedFileTypeDetect
  autocmd!
  autocmd BufNewFile,BufRead *.uml,*.puml,*.plantuml,*.pu setfiletype plantuml
augroup END

" Global Settings
colorscheme desert
set title
set number
set tabstop=8
set autoindent
set smartindent
set showmatch
set matchtime=1
set t_Co=256
set clipboard=unnamed,autoselect
set list
set listchars=tab:>\ ,trail:_,nbsp:%,extends:>,precedes:<
set cursorline
set laststatus=2
set background=dark
set incsearch
set ruler
syntax on
set hidden
set nowritebackup
set noundofile
set nobackup
set cmdheight=2
set fileencodings=utf-8,sjis,cp932,euc-jp
set wildmenu
set signcolumn=yes
set ambiwidth=double

