#!/bin/bash

if [[ -f ~/.bashrc ]]; then
	source ~/.bashrc
fi
export PATH="/opt/homebrew/bin:~/Apps/flutter/bin:$PATH"

export CHROME_EXECUTABLE='/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'
