" My vimrc
" vim:set ts=8 sts=2 sw=2 tw=0:
set nocompatible

" Set for Windows environment
if has('win32') || has('win64')
  "let $HOME='system('echo "C:/Users/$(whoami)"')'
  let g:coc_node_path="C:/Program\ Files/nodejs/node.exe"
endif

" Set for macOS environment
if has('mac')
  let g:coc_node_path="~/.nodebrew/current/bin/node"
endif

" Plugins dir
let s:plugin_dir = expand('~/.vim/bundle/')
" Add runtimepath the dir to install dein.vim
let s:dein_dir = s:plugin_dir . 'repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . s:dein_dir

" If not installed dein.vim, install when vim is opened
augroup PluginInstall
  autocmd!
    autocmd VimEnter * if dein#check_install() | call dein#install() | endif
augroup END

if !isdirectory(s:dein_dir)
      call mkdir(s:dein_dir, 'p')
        silent execute printf('!git clone %s %s', 'https://github.com/Shougo/dein.vim', s:dein_dir)
endif

if dein#load_state(s:plugin_dir)
  call dein#begin(s:plugin_dir)

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on

" Global Settings
colorscheme desert
set title
set number
set tabstop=8
set autoindent
set smartindent
set showmatch
set matchtime=1
set t_Co=256
set clipboard=unnamed,autoselect
set list
set listchars=tab:>\ ,trail:_,nbsp:%,extends:>,precedes:<
set cursorline
set laststatus=2
set background=dark
set incsearch
set ruler
syntax on
set hidden
set nowritebackup
set noundofile
set nobackup
set cmdheight=2
set fileencodings=utf-8,sjis,cp932,euc-jp

" PlantUML Settings
let g:plantuml_executable_script = expand('$HOME/dotfiles/common/plantuml/txt2plantuml.sh')

" Cheetsheat
let g:cheatsheet#cheat_file = '~/dotfiles/common/vim/cheatsheet.md'

" sonictemplate-vim
let g:sonictemplate_vim_template_dir = '~/dotfiles/common/vim/template'

" Markdown Settings
augroup MarkdownSettings
  autocmd!
  autocmd BufNewFile,BufRead *.{md,mkd} set filetype=markdown
  nnoremap <silent> <C-p> :PrevimOpen<CR>
  let g:vim_markdown_folding_disabled = 1
  let g:previm_enable_realtime = 1
  if has('win32') || ('win64')
    let g:previm_open_cmd = 'C:\\Program\ Files\ (x86)\\Mozilla\ Firefox\\firefox.exe'
  elseif has('mac')
    let g:previm_open_cmd = 'open -a Firefox.app'
  else
    let g:previm_open_cmd = ''
  endif
augroup END

" NERDTree Settings
let NERDTreeShowHidden = 1
let NERDTreeIgnore = [
      \ 'NTUSER.*$',
      \ '.[oa]$'
      \]
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | execute 'NERDTree' | endif

