# Homebrew
export PATH="/opt/homebrew/bin:$PATH"

# bash-completion
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] \
	&& . "/opt/homebrew/etc/profile.d/bash_completion.sh"

# Node.js
export PATH="$PATH:/Users/$(whoami)/.nodebrew/current/bin"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"

# Flutter
if [[ ${DOTFILES_ENV_CONFIG_FLUTTER_ENABLE} = "y" ]]; then
	export FVM_CACHE_PATH="$HOME/.fvm"
	export PATH="$PATH:$HOME/.pub-cache/bin:$FVM_HOME/default/bin"
	export CHROME_EXECUTABLE='/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'
fi

# Rancher Desktop
[[ ${DOTFILES_ENV_CONFIG_RANCHER_DESKTOP_ENABLE} = "y" ]] && [[ -d "$HOME/.rd/bin" ]] \
	&& export PATH="$PATH:$HOME/.rd/bin"

