# ls command aliases
alias l='ls -G'
alias ls='ls -G'
alias ll='ls -laG'


# Git Prompt
if [ -f /usr/local/git/git-completion.bash ]; then
	source /usr/local/git/git-completion.bash
elif [ -f /usr/local/git/contrib/completion/git-completion.bash ]; then
	source /usr/local/git/contrib/completion/git-completion.bash
elif [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	source /usr/local/etc/bash_completion.d/git-completion.bash
fi

if [ -f /usr/local/git/git-prompt.sh ]; then
	source /usr/local/git/git-prompt.sh
elif [ -f /usr/local/git/contrib/completion/git-prompt.sh ]; then
	source /usr/local/git/contrib/completion/git-prompt.sh
elif [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
	source /usr/local/etc/bash_completion.d/git-prompt.sh
fi

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

GIT_PS1_SHOWDIRTYSTATE=true

# tmux
alias tm='tmux new-session \; source-file ~/dotfiles/common/tmux/tmux.startup'
alias tml='tmux ls'
alias tma='tmux attach'
alias tmd='tmux detach'

# flutter
alias flutter='fvm flutter'
alias dart='fvm dart'

# homebrew-bundle
alias bb='brew bundle --verbose --file ~/dotfiles/homebrew/Brewfile'

