# Homebrew
export PATH="/opt/homebrew/bin:$PATH"

# Node.js
export PATH="$PATH:/Users/$(whoami)/.nodebrew/current/bin"

# Ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"

# Flutter
if [[ ${DOTFILES_ENV_CONFIG_FLUTTER_ENABLE} = "y" ]]; then
	export FVM_HOME="$HOME/.fvm"
	export PATH="$PATH:$HOME/.pub-cache/bin:$FVM_HOME/default/bin"
	export CHROME_EXECUTABLE='/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'
fi

